name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CIBW_BUILD_VERBOSITY: 1

jobs:
  build_test_py38:
    name: Python 3.8 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]  # macos: x86_64

    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: cp38-{manylinux_x86_64,win_amd64,macosx_x86_64}
          CIBW_TEST_COMMAND: python {project}/test/test.py && pip install "h5py==3.0.0" && python {project}/test/test.py

  build_test:
    name: ${{ matrix.cibw_build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_build: "cp310-manylinux_x86_64"
            OLDEST_DEPENDENCIES: 'h5py==3.6.0 "numpy<2"'
          - os: windows-latest
            cibw_build: "cp311-win_amd64"
            OLDEST_DEPENDENCIES: 'h5py==3.8.0 "numpy<2"'
          - os: macos-latest
            cibw_build: "cp312-macosx_arm64"
            OLDEST_DEPENDENCIES: 'h5py==3.10.0 "numpy<2"'

    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_TEST_EXTRAS: test  # To run tests
          CIBW_TEST_COMMAND: python {project}/test/test.py && pip install ${{ matrix.OLDEST_DEPENDENCIES }} && python {project}/test/test.py
